"""Regenerate static pages from editorial JSON. No third-party dependencies."""
from pathlib import Path
from html import escape as e
import json
ROOT=Path(__file__).resolve().parents[1]
data=json.loads((ROOT/'data/timeline.json').read_text())
assets=json.loads((ROOT/'data/assets.json').read_text())
def image(name,alt,cls=''):
 a=assets[name]
 srcset=(f'{a["smallSrc"]} {a["smallWidth"]}w, {a["src"]} {a["width"]}w' if a['smallWidth'] != a['width'] else f'{a["src"]} {a["width"]}w')
 return f'<img class="{cls}" src="assets/{name}.webp" srcset="{srcset}" sizes="(max-width: 760px) 100vw, 55vw" alt="{e(alt)}" width="{a["width"]}" height="{a["height"]}" loading="lazy" decoding="async">'
nav=''.join(f'<a href="#{next(x["id"] for x in data["events"] if x["era"]==era["id"])}" data-era="{era["id"]}"><span>{i+1:02}</span> {era["label"]}</a>' for i,era in enumerate(data['eras']))
sections=[]
for i,x in enumerate(data['events']):
 sources=''.join((f'<li><a href="{e(data["sources"][s]["url"])}" target="_blank" rel="noopener">{e(data["sources"][s]["title"])} ↗</a>' if data["sources"][s].get("url") else f'<li><span>{e(data["sources"][s]["title"])}</span>') + f'<small>{e(data["sources"][s]["type"])}</small></li>' for s in x['sources'])
 notes=f'<details><summary>Sources &amp; context</summary><p>{e(x["status"])}</p><ul>{sources}</ul>'+ (f'<p>{e(x["note"])}</p>' if x.get('note') else '')+'</details>'
 visual=f'<figure><div class="depth-frame">{image(x["image"],x["caption"])}</div><figcaption>{e(x["caption"])}</figcaption></figure>' if x.get('image') else f'<div class="type-plate" aria-hidden="true"><span>{i+1:02} / 12</span><strong>{e(x["motif"])}</strong><i>Damien · A living history</i></div>'
 sections.append(f'''<section class="chapter {'reverse' if i%2 else ''} {'dark' if i in [1,4,8,11] else ''}" id="{x['id']}" data-era="{x['era']}" aria-labelledby="heading-{x['id']}"><div class="chapter-copy"><p class="kicker">{i+1:02} / 12 &nbsp; · &nbsp; {e(x['eyebrow'])}</p><p class="date">{e(x['date'])}</p><h2 id="heading-{x['id']}">{e(x['title'])}</h2><p class="body-copy">{e(x['body'])}</p>{'<button class="text-link" data-open="map-dialog">Explore the map <span>↗</span></button>' if x.get('exhibit') else ''}{notes}</div><div class="chapter-visual">{visual}</div></section>''')
categories=''.join(f'<li><span>0{i+1}</span><h3>{e(c)}</h3><p>Stories to come</p></li>' for i,c in enumerate(data['alumni']['categories']))
html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#242322"><meta name="description" content="Explore the people, land and shared purpose behind Damien Memorial School. A living history of Damien and Kapālama."><title>Damien · A Living History</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head>
<body><a class="skip" href="#story">Skip to the history</a><header><a class="brand" href="#top"><span class="monogram">D</span><span>DAMIEN<small>A LIVING HISTORY</small></span></a><nav aria-label="Main navigation"><a href="#story">The story</a><button data-open="map-dialog">The map ↗</button><a href="#alumni">Our people</a></nav><span class="edition">PROTOTYPE 01</span></header>
<main id="top"><section class="hero" aria-labelledby="hero-title"><img class="hero-image" src="assets/water.webp" srcset="assets/water-small.webp 800w, assets/water.webp 1800w" sizes="100vw" alt="An archival view along Niuhelewai, with homes and vegetation beside the water" fetchpriority="high"><div class="hero-shade"></div><div class="hero-copy"><p class="kicker">DAMIEN MEMORIAL SCHOOL &nbsp; / &nbsp; KAPĀLAMA, OʻAHU</p><h1 id="hero-title">A place.<br>A purpose.<br><em>A legacy.</em></h1><p>Before a school, a living landscape.<br>Beyond a campus, generations of stories.</p><a class="begin" href="#story">Begin the story <span>↓</span></a></div><div class="hero-caption"><span>FROM THE DAMIEN ARCHIVE</span><p>Niuhelewai · photograph date unconfirmed</p></div><span class="hero-index" aria-hidden="true">01 — ∞</span></section>
<div class="era-bar"><nav aria-label="Story chapters">{nav}</nav><div class="progress-track"><div id="progress"></div></div><span id="progress-text" class="sr-only">Story progress</span></div>
<section class="intro" id="story"><p class="kicker">PEOPLE · PLACE · PURPOSE</p><h2>Every place holds<br><em>more than one history.</em></h2><div><p>Two lives of service. An inhabited and cultivated ʻāina. A school built through the work of a community.</p><p>Follow these intertwined stories from Damien and Edmund Rice back to the lands of Kapālama, then forward to the Monarchs of today.</p><span class="reading-note">12 moments &nbsp; · &nbsp; A thematic journey through time</span></div></section>
{''.join(sections)}
<section id="alumni" class="alumni" aria-labelledby="alumni-title"><div class="alumni-head"><p class="kicker">THE ALUMNI HALL OF FAME</p><span class="pill">EXHIBIT IN DEVELOPMENT</span></div><h2 id="alumni-title">{e(data['alumni']['title'])}</h2><p>{e(data['alumni']['description'])}</p><ul class="alumni-grid">{categories}</ul><p class="quiet">Profiles will appear here as stories and archival materials are prepared. No inductees are listed in this prototype.</p></section>
<section class="closing"><p class="kicker">THE NEXT CHAPTER IS OURS</p><h2>Remember where.<br><em>Imagine what’s next.</em></h2><a class="text-link" href="#top">Return to the beginning ↑</a></section></main>
<footer><span>DAMIEN MONARCH MEDIA</span><p>Prototype 1 · September 2026<br>Research-led storytelling. An evolving archive.</p><a href="data/timeline.json">Timeline data &amp; source register ↗</a></footer>
<dialog id="map-dialog" aria-labelledby="map-title"><div class="exhibit-header"><div><p class="kicker">THE MAP ROOM · EXHIBIT 01</p><h2 id="map-title">Kapālama, in layers.</h2></div><button class="close" data-close aria-label="Close map and return to story">Close ×</button></div><div class="exhibit-layout"><div class="map-space"><div class="map-toolbar" role="group" aria-label="Map controls"><button id="zoom-out" aria-label="Zoom out">−</button><output id="zoom-label" aria-live="polite">100%</output><button id="zoom-in" aria-label="Zoom in">+</button><button id="reset-map">Reset</button></div><div id="map-viewport" tabindex="0" role="region" aria-label="Zoomable 1885 Kapālama map" aria-describedby="map-help"><img id="map-image" alt="Project-colored detail of the hand-drawn Kapālama cadastral working sheet, with award parcels and water highlights" draggable="false"></div><p id="map-help">Drag to pan · + / − to zoom · Arrow keys to pan · 0 to reset</p><div class="pan-controls" role="group" aria-label="Pan map"><button data-pan="left" aria-label="Pan left">←</button><button data-pan="up" aria-label="Pan up">↑</button><button data-pan="down" aria-label="Pan down">↓</button><button data-pan="right" aria-label="Pan right">→</button></div></div><aside><p class="kicker">1885 · REG. MAP 1039</p><h3>Read the layers.</h3><p>The hand-drawn cadastral map is shown here in the project’s colored research version. Parcel colors and blue water highlights are modern additions to the historical base.</p><details open><summary>Land &amp; people</summary><p>Kaniniu, Hikiʻau, Waiwaiʻole and Nohunohu appear in the project’s researched award network. A single award can include separate ʻāpana.</p></details><details><summary>Water &amp; cultivation</summary><p>Read the loʻi and ʻauwai alongside the parcels. Water connects places that later streets can make seem separate.</p></details><details><summary>What this exhibit can tell us</summary><p>This is a prototype image viewer. Parcel hotspots, georeferenced overlays and claimant records are future additions. Research colors are interpretive and do not establish modern surveyed property boundaries.</p></details><a class="text-link" href="{data['sources']['colored']['url']}" target="_blank" rel="noopener">Open archival source ↗</a></aside></div></dialog>
<noscript><div class="noscript">The full story is available without JavaScript. For the map, <a href="assets/map.webp">open the archival image</a>. Interactive navigation progress and map controls require JavaScript.</div></noscript></body></html>'''
(ROOT/'index.html').write_text(html)
print(f'Built {len(data["events"])} events.')
